# conda env create|update --file environment.yml
name: aucanalysis
dependencies:
- python=3.7
- pip
- pip:
  - '--editable=.'
  - flake8
  - flake8-quotes
  - jupyter
  - matplotlib
  - numpy==1.16.*
  - pandas==0.24.1
  - pytest
  - pytest-mock
  - scipy
  - seaborn
  - sklearn
  - torch
  - dateutil
  - urllib
  - requests